package constants

const (

	// Window
	WINDOW_WIDTH  = 1280
	WINDOW_HEIGHT = 720

	// Game map vars
	GAME_MAP_BLOCK_SIZE     = 50
	GAME_MAP_SIZE_IN_BLOCKS = 10
	GAME_MAP_SIZE_IN_PX     = GAME_MAP_BLOCK_SIZE * GAME_MAP_SIZE_IN_BLOCKS
	GAME_MAP_START_X        = (WINDOW_WIDTH - GAME_MAP_SIZE_IN_PX) / 2
	GAME_MAP_START_Y        = (WINDOW_HEIGHT - GAME_MAP_SIZE_IN_PX) / 2
)
